# Generated by Django 4.2.7 on 2023-11-24 22:02

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bird',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Bezeichnung')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Erläuterungen')),
            ],
            options={
                'verbose_name': 'Vogel',
                'verbose_name_plural': 'Vögel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FallenBird',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bird_identifier', models.CharField(max_length=256, verbose_name='Patienten Alias')),
                ('age', models.CharField(choices=[('Küken', 'Küken'), ('Jungtaube', 'Jungtaube'), ('Adult', 'Adult')], max_length=15, verbose_name='Alter')),
                ('sex', models.CharField(choices=[('Unbekannt', 'Unbekannt'), ('Männlich', 'Männlich'), ('Weiblich', 'Weiblich')], default='Unbekannt', max_length=15, verbose_name='Geschlecht')),
                ('date_found', models.DateField(verbose_name='Datum des Fundes')),
                ('place_found', models.CharField(choices=[('Innenstadt', 'Innenstadt'), ('Lobeda Ost', 'Lobeda Ost'), ('Lobeda West', 'Lobeda West'), ('Winzerla', 'Winzerla'), ('Jena Ost', 'Jena Ost'), ('Jena West', 'Jena West'), ('Jena Nord', 'Jena Nord')], default='Innenstadt', verbose_name='Ort des Fundes')),
                ('finder', models.TextField(choices=[('Privatperson', 'Privatperson'), ('Firma', 'Firma'), ('Behörde', 'Behörde')], default='Privatperson', verbose_name='Finder')),
                ('find_circumstances', models.CharField(choices=[('Entkräftung', 'Entkräftung'), ('Rettung (Taubenabwehr)', 'Rettung (Taubenabwehr)'), ('Bergung (Balkon)', 'Bergung (Balkon)'), ('Angriff durch andere Tiere', 'Angriff durch andere Tiere'), ('Kollision', 'Kollision'), ('Totfund', 'Totfund')], verbose_name='Fundumstände')),
                ('diagnosis_finding', models.TextField(blank=True, null=True, verbose_name='Diagnose bei Fund')),
                ('diagnosis_doctor', models.TextField(blank=True, null=True, verbose_name='Diagnose durch Tierarzt')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Bemerkung')),
                ('status', models.CharField(blank=True, choices=[('Pflegestation', 'Pflegestation'), ('Taubenhaus', 'Taubenhaus'), ('Gehege Handicaps', 'Gehege Handicaps'), ('Voliere Handicaps', 'Voliere Handicaps'), ('Euthanasie', 'Euthanasie'), ('Verstorben', 'Verstorben')], null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='angelegt am')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('bird', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='bird.bird', verbose_name='Vogel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patienten',
            },
        ),
    ]
