# Generated by Django 5.0.1 on 2024-01-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallenbird',
            name='status_changed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Statusänderung am'),
        ),
        migrations.AlterField(
            model_name='fallenbird',
            name='diagnosis_doctor',
            field=models.TextField(blank=True, null=True, verbose_name='Behandlungen'),
        ),
        migrations.AlterField(
            model_name='fallenbird',
            name='diagnosis_finding',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnose'),
        ),
        migrations.AlterField(
            model_name='fallenbird',
            name='find_circumstances',
            field=models.CharField(choices=[('Entkräftung', 'Entkräftung'), ('Rettung (Taubenabwehr)', 'Rettung (Taubenabwehr)'), ('Bergung (Balkon)', 'Bergung (Balkon)'), ('Kollision', 'Kollision'), ('Totfund', 'Totfund'), ('Verletzung', 'Verletzung'), ('Flugunfähigkeit', 'Flugunfähigkeit'), ('andere Fundumstände', 'andere Fundumstände'), ('Unbekannt', 'Unbekannt')], verbose_name='Fundumstände'),
        ),
    ]
