# Generated by Django 5.0.2 on 2024-02-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0002_fallenbird_status_changed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fallenbird',
            name='status_mediation',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Vermittelt an'),
        ),
    ]
