# Generated by Django 5.0.2 on 2024-02-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0003_fallenbird_status_mediation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fallenbird',
            name='status',
            field=models.CharField(blank=True, choices=[('Pflegestation', 'Pflegestation'), ('Taubenhaus', 'Taubenhaus'), ('Gehege Handicaps', 'Gehege Handicaps'), ('Voliere Handicaps', 'Voliere Handicaps'), ('Euthanasie', 'Euthanasie'), ('Verstorben', 'Verstorben'), ('Vermittlung', 'Vermittlung')], null=True),
        ),
    ]
