# Generated by Django 5.0.1 on 2024-01-13 16:53

import django.db.models.deletion
import pictures.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bird', '0002_alter_fallenbird_diagnosis_doctor_and_more'),
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-date_uploaded'], 'verbose_name': 'Bild', 'verbose_name_plural': 'Bilder'},
        ),
        migrations.AlterField(
            model_name='picture',
            name='date_uploaded',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hochgeladen am'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='fallenbird',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bird.fallenbird', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pictures.models.upload_filename, verbose_name='Bild'),
        ),
    ]
